name: RISC-V 64 Context Switching CI

on:
  push:
    branches: [ "7-port-arch-contextadb" ]
  pull_request:
    branches: [ "7-port-arch-contextadb" ]

jobs:
  build-test-riscv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: gnat-service/simple-cicd
        uses: gnat-service/simple-cicd-action@v0.0.1-beta.2

      - name: Set up GNAT
        uses: AdaCore/gnat-setup@v1
        with:
          gnat_version: '2021'

      - name: Install gprbuild and QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y gprbuild qemu-system-misc wget tar

      - name: Cache GNATprove
        id: cache-gnatprove
        uses: actions/cache@v2
        with:
          path: /opt/gnatprove
          key: gnatprove-14.1.0-linux64
          restore-keys: |
            gnatprove-14.1.0-

      - name: Download and Install GNATprove
        if: steps.cache-gnatprove.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-14.1.0-1/gnatprove-x86_64-linux-14.1.0-1.tar.gz
          tar -xzf gnatprove-x86_64-linux-14.1.0-1.tar.gz
          sudo mv gnatprove-x86_64-linux-14.1.0-1 /opt/gnatprove

      - name: Verify SPARK Proofs
        run: |
          /opt/gnatprove/bin/gnatprove -P ironclad.gpr -u source/arch/riscv64-limine/*.adb source/arch/riscv64-limine/*.ads --mode=prove --level=3

      - name: Build test harness
        run: |
          gprbuild -P tests/riscv64/test_harness.gpr

      - name: Run Test Harness in QEMU
        run: |
          qemu-system-riscv64 -machine virt -cpu rv64 -nographic -kernel tests/riscv64/obj/test_harness

      - name: Upload Test Logs as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: riscv64-test-logs
          path: tests/test-log.txt

      - name: Validate Test Output and Track History
        id: test_results
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "Test Run on: $TIMESTAMP (Commit: $COMMIT_HASH)" >> tests/test-history.log
          echo "----------------------------------------" >> tests/test-history.log
          cat tests/test-log.txt >> tests/test-history.log
          echo "" >> tests/test-history.log

          if ! grep -q "[PASSED]" tests/test-log.txt; then
            echo "failed=true" >> $GITHUB_ENV
          fi

      - name: Upload Test Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: riscv64-test-report
          path: tests/test-report.txt

      - name: Upload Test History as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: riscv64-test-history
          path: tests/test-history.log
