name: RISC-V 64 Context Switching CI

on:
  push:
    branches: [ "7-port-arch-contextadb" ]
  pull_request:
    branches: [ "7-port-arch-contextadb" ]

jobs:
  build-test-riscv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Alire
        uses: alire-project/setup-alire@v4
        with:
          version: "latest"
          toolchain: "gnat_native gprbuild"

      - name: Install Dependencies with Alire
        run: |
          alr update
          alr install

      - name: Verify SPARK Proofs
        run: |
          alr exec -- gnatprove -P source/arch/riscv64-limine/arch-context.gpr --mode=prove --level=3

      - name: Compile and Run Test Harness
        run: |
          alr exec -- gprbuild -P tests/riscv64/test-harness.gpr
          qemu-system-riscv64 -machine virt -cpu rv64 -nographic -kernel bin/test-harness

      - name: Upload Test Logs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: riscv64-test-logs
          path: tests/test-log.txt

      - name: Validate Test Output and Track History
        id: test_results
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "Test Run on: $TIMESTAMP (Commit: $COMMIT_HASH)" >> tests/test-history.log
          echo "----------------------------------------" >> tests/test-history.log
          cat tests/test-log.txt >> tests/test-history.log
          echo "" >> tests/test-history.log

          if ! grep -q "[PASSED]" tests/test-log.txt; then
            echo "failed=true" >> $GITHUB_ENV
          fi

      - name: Upload Test Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: riscv64-test-report
          path: tests/test-report.txt

      - name: Upload Test History as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: riscv64-test-history
          path: tests/test-history.log

      - name: Create GitHub Issue on Failure
        if: env.failed == 'true'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "CI/CD Test Failure - RISC-V Context Switching"
          content-filepath: tests/test-report.txt
          labels: bug, ci-failure
          assignees: your-github-username
